### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hectorateci**
Added new details for the mapping

### CODE REVIEW

**Review by hcadavid — CHANGES_REQUESTED** [review]
It is still not clear. Please update.

**Review by hectorateci — COMMENTED** [review]
Added another line

**Review by hcadavid — APPROVED** [review]

**Comment by hcadavid** [comment]
Added comments

**Comment by hectorateci** [comment]
You closed my PR. Reopened

**Review by hcadavid — APPROVED** [review]
Accepted

**Pull request merged**
